#Assignment sql
#Functions
create database sakila;
use sakila;

#Question 1:
#Retrieve the total number of rentals made in the Sakila database.
select * from rental;

#Question 2:
#Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(rental_duration) as avg_rentalduration
from film;

#String Functions:
#Question 3:
#Display the first name and last name of customers in uppercase.
select upper(first_name),upper(last_name)
from customer;

#Question 4:
#Extract the month from the rental date and display it alongside the rental ID.
select rental_id,month(rental_date) as month
from rental;

#GROUP BY:
#Question 5:
#Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select customer_id,count(rental_id)
from rental
group by customer_id;

#Question 6:
#Find the total revenue generated by each store.
select store.store_id,sum(payment.amount)
from store
inner join staff
on store.store_id=staff.store_id
inner join payment
on staff.staff_id=payment.staff_id
group by store.store_id;

#Question 7:
#Determine the total number of rentals for each category of movies
select category.name,count(rental.rental_id) as total_rental
from category
inner join film_category
on film_category.category_id=category.category_id
inner join film
on film.film_id=film_category.film_id
inner join inventory
on inventory.film_id=film.film_id
inner join rental
on rental.inventory_id=inventory.inventory_id
group by category.name
order by total_rental desc;

#Question 8:
#Find the average rental rate of movies in each language
select language.name,avg(film.rental_rate) 
from language
inner join film
on film.language_id=language.language_id
group by language.name;

